---
- name: Create a security group
  local_action: 
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group for webserver Servers
    region: "{{ region }}"
    rules: "{{ sec_grp_in }}"
    rules_egress: "{{ sec_grp_out }}"
  register: basic_firewall

- name: Launch the new EC2 Instance for {{ inventory_group }}
  local_action: ec2 
                group={{ security_group }} 
                instance_type={{ instance_type}} 
                image={{ image }} 
                wait=true 
                region={{ region }} 
                keypair={{ keypair }}
                count={{count}}
  register: ec2

- name: Add the newly created EC2 instance(s) to the local host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ inventory_group }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2.instances }}"

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "{{ ec2tag }}"
